# https://github.com/iamawatermelo/wakapi-anyide v0.6.6

[meta]
version = 1
watchers = ['files']

[files]
include = [".devcontainer", "/docs", "/lib", "/manifests", "package.json", ".env*", "tsconfig.json", "prisma/", "*.md", "app.ts"]  # files to include in tracking
exclude = ["/node_modules"]  # files to exclude in tracking
exclude_files = [".gitignore"]  # files whose contents will be used to exclude other files from tracking
exclude_binary_files = true  # whether to ignore binary files
# language_mapping = {".kicad_sch" = "Kicad Schematic"} # custom language mapping

[project]
name = "@andreijiroh-dev/leeksbot"  # your project name
